config/routes.rb
Rails.application.routes.draw do
  
  
  ActiveAdmin.routes(self)
  get 'welcome/index'

  get 'admin' => 'admin#index'

  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end

    get 'auth/:provider/callback' => 'sessions#fb_create'
    get 'auth/failure' => redirect('/')
    get 'signout_fb' => 'sessions#fb_destroy'



  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  resources :users
  resources :areas 
  resources :line_items
  resources :carts
  resources :restaurants do 
      resources :restaurant_images
      resources :reviews, except: [:show]
      resources :orders
      resources :categories do 
        resources :foods
      end
      resources :foods
      resources :opening_hours   
  end
  get 'restaurants/info/:id', to: 'restaurants#info', as: :restaurant_info

  root 'welcome#index'

  resources :foods do
  	get :who_bought, on: :member
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
	
	def add_food(food)
		current_item = line_items.find_by(food_id: food.id)
		if current_item
			current_item.quantity += 1 
		else 
			current_item = line_items.build(food_id: food.id)
		end
		current_item
	end

	def total_price 
		line_items.to_a.sum { |item| item.total_price }
	end



	def remove_food(food)
	    current_item = line_items.find_by(food_id: food.id)
		if current_item.quantity > 1
			current_item.quantity -= 1
		elsif current_item.quantity = 1
		    current_item.destroy
		end
	   	current_item
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end   

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)


    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to restaurant }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to restaurant_index_url, notice: 'Invalid cart'
    end 
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart__header__head__delivery-time"> 
    <div class="cart__header__head__delivery-time__label">Livraison dans environ </div> 
        <div class="cart__header__head__delivery-time__time"> 
            <span class="delivery_time_minutes"><%= @restaurant.estimated_delivery_time %></span> 
            <span class="delivery_time_label">minutes</span> 
        </div> 	
</div> 
 
<div class="clear"></div> 
<h2>Votre commande </h2>
<div class="cart__products" style="max-height: none;"> 
    <table> 
        <tbody> 
        	<%= render(cart.line_items) %> 
        </tbody> 
    </table> 
</div> 

<div class="cart__summary"> 
    <table> 
        <tbody> 
            <tr class="subtotal"> 
                <td></td> 
                <td>Sous total</td> 
                <td class="price"><%= number_to_currency(cart.total_price, unit: " ")%> DH</td> 
            </tr> 
            <tr class="deliverey-fee"> 
                <td></td> 
                <td class="title">Frais de livraison</td> 
                <td class="price"><%= number_to_currency(@restaurant.delivery_fee, unit: " ")%> DH</td> 
            </tr> 
            <tr class="vat"> 
                <td></td> 
                <td class="title">+ Vat</td> 
                <td class="price">3.11 DH</td> 
            </tr> 
            <tr class="total"> 
                <td></td> 
                <td class="title">Total</td> 
                <td class="total-price"><%= number_to_currency(@restaurant.delivery_fee + 3.11 + cart.total_price, unit: " ")%> DH</td> 
                
            </tr> 
        </tbody> 
    </table> 
</div> 


<div class="cart__checkout">    
        <%= link_to "Passer la commande", new_restaurant_order_path(@restaurant), method: :get, class: "btn btn-primary btn-block", id: "btn-checkout" %> 
</div>



<% if !logged_in? %> 
<h5 class="check-sentence">Please <%= link_to "log in", login_path %> or <%= link_to "register", new_user_path %> to place your order</h5>
<% end %>

<div class="cart__empty cart__empty--outside"> 
    <ul class="cart__empty__elements"> 
        <li> 
            <span class="title">Frais de livraison:</span> 
            <span class="value"><%= number_to_currency(@restaurant.delivery_fee, unit: " ") %>DH</span> 
        </li>
        <li> 
            <span class="title">minimum de livraison:</span> 
            <span class="value"><%= number_to_currency(@restaurant.delivery_minimum, unit: " ") %>DH</span> 
        </li>  
    </ul> 
</div> 

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>
      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @cart %>