config/routes.rb
Rails.application.routes.draw do
  
  
  ActiveAdmin.routes(self)
  get 'welcome/index'

  get 'admin' => 'admin#index'

  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end

    get 'auth/:provider/callback' => 'sessions#fb_create'
    get 'auth/failure' => redirect('/')
    get 'signout_fb' => 'sessions#fb_destroy'



  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  resources :users
  resources :areas 
  resources :line_items
  resources :carts
  resources :restaurants do 
      resources :restaurant_images
      resources :reviews, except: [:show]
      resources :orders
      resources :categories do 
        resources :foods
      end
      resources :foods
      resources :opening_hours   
  end
  get 'restaurants/info/:id', to: 'restaurants#info', as: :restaurant_info

  root 'welcome#index'

  resources :foods do
  	get :who_bought, on: :member
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
	has_many :line_items
	has_many :orders, through: :line_items
	belongs_to :user
	belongs_to :restaurant
	belongs_to :category

	before_destroy :ensure_not_referenced_by_any_line_item
	
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i, 
		message: 'must be a URL for GIF, JPG, or PNG image.'
	}

	private 
		# ensure that there are no line items referencing this product 
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty? 
				errors.add(:base, 'Line Items present')
				throw :abort
			end 
		end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  skip_before_action :authorize, only: :index
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant
  before_action :set_category 
  before_action :set_reviews
  include CurrentCart
  before_action :set_cart

  # GET /foods
  # GET /foods.json
  def index
    @categories = Category.where(restaurant_id: @restaurant.id).order("created_at DESC")
    if @category
      @foods = @category.foods
    else
      @foods = @restaurant.foods
    end

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end 

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
    @categories = Category.where(restaurant_id: @restaurant.id).order("created_at DESC").all.map{|c| [ c.name, c.id ] }
  end

  # GET /foods/1/edit
  def edit
    @categories = Category.where(restaurant_id: @restaurant.id).order("created_at DESC").all.map{|c| [ c.name, c.id ] }
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id 
    @food.restaurant_id = @restaurant.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to @restaurant }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    @food.category_id = params[:category_id]
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @restaurant, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }

        @foods = Food.all 
        ActionCable.server.broadcast 'foods', html: render_to_string('restaurants/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def who_bought 
    @food = Food.find(params[:id])
    @latest_order = @food.orders.order(:updated_at).last 
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to @restaurant, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_reviews
      @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    end

    def set_food
      @food = Food.find(params[:id])
    end

    def set_restaurant 
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def set_category
      @category = Category.find(params[:category_id]) if params[:category_id]
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:title, :description, :image_url, :price, :category_id)
    end
end
  

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-offeset-md-3">
      <%= form_for([@restaurant, @category, @food]) do |f| %>
      <% if food.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

          <ul>
          <% food.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :category_id %>
        <%= f.collection_select :category_id, @restaurant.categories.all, :id, :name, {prompt: "categorie" } %>
      </div>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label :image_url %>
        <%= f.text_field :image_url %>
      </div>

      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price %>
      </div>



      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="jumbotron" id="jumbotron1">
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<h1>Editing Food</h1>

			<%= render 'form', food: @food %>

			<%= link_to 'Show', @food %> |
			<%= link_to 'Back', restaurant_path(@restaurant) %>
		</div>
	</div>
</div>

app/views/foods/index.html.erb
<div class="restaurant-show-page">

<div class="container">

  <div class="restaurant-index-wrapper">

<h1><%= @restaurant.name %></h1>
  <div class="row">
    <div class="col-md-8">
        <div class="vendor-tabs">
          <ul class="nav nav-tabs vendor-tabs">
              <li class="<%=is_active('index')%>">
                <%= link_to 'Menu', restaurant_foods_path(@restaurant) %> 
              </li>
              <li>
                <%= link_to 'Commentaires', restaurant_reviews_path(@restaurant) %> 
              </li>
              <li>
                <%= link_to 'Info', restaurant_info_path(@restaurant) %> 
              </li>
          </ul>
        </div> 

        <% @categories.each do |category| %>
          <% if !category.foods.blank? %>
            <h3 class="menu-category-title"><%= category.name %></h3>
            <% category.foods.each do |food| %>   
              <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-2">
                  <%= image_tag(food.image_url, class: "food-image") %>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                  <h3 class="food-title"><%= food.title %></h3>
                  <p class="food-description"><%= sanitize(food.description) %></p>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-4">
                <p class="price">
                  <span class="food-price"><%= number_to_currency(food.price, unit: "") %> DH</span>
                  <span><%= button_to '+', line_items_path(food_id: food), remote: true, class: "btn-plus" %></span>
                </p>
                </div>
              </div>
            <% end %>   
          <% end %>
        <% end %>
        
    </div>
    <div class="col-md-4">
    <div class="right-side">
      <div class="logo-restaurant">
        <%= image_tag @restaurant.image.url(:medium) , class: "vendor-image" %>
      </div>
      <div class="rating">
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em class="reviews_length"><%= "(#{@reviews.length})" %></em>
      </div>
      </div>
      <% if @cart %>
          <%= render @cart %>
      <% end %>  
    </div>
  </div>
</div>
</div>

  </div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
</script>

app/views/foods/new.html.erb
<div class="jumbotron" id="jumbotron1">
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<h1>New Food</h1>

			<%= render 'form', food: @food %>

			<%= link_to 'Back', restaurant_path(@restaurant), class: "add-link" %>
		</div>
	</div>
</div>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @food.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>