config/routes.rb
Rails.application.routes.draw do
  
  
  ActiveAdmin.routes(self)
  get 'welcome/index'

  get 'admin' => 'admin#index'

  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create
    delete 'logout' => :destroy
  end

    get 'auth/:provider/callback' => 'sessions#fb_create'
    get 'auth/failure' => redirect('/')
    get 'signout_fb' => 'sessions#fb_destroy'



  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  resources :users
  resources :areas 
  resources :line_items
  resources :carts
  resources :restaurants do 
      resources :restaurant_images
      resources :reviews, except: [:show]
      resources :orders
      resources :categories do 
        resources :foods
      end
      resources :foods
      resources :opening_hours   
  end
  get 'restaurants/info/:id', to: 'restaurants#info', as: :restaurant_info

  root 'welcome#index'

  resources :foods do
  	get :who_bought, on: :member
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
	has_and_belongs_to_many :restaurants, dependent: :destroy
end

app/models/authorization.rb
class Authorization < ApplicationRecord
	belongs_to :user
    validates :provider, :uid, :presence => true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
	
	def add_food(food)
		current_item = line_items.find_by(food_id: food.id)
		if current_item
			current_item.quantity += 1 
		else 
			current_item = line_items.build(food_id: food.id)
		end
		current_item
	end

	def total_price 
		line_items.to_a.sum { |item| item.total_price }
	end



	def remove_food(food)
	    current_item = line_items.find_by(food_id: food.id)
		if current_item.quantity > 1
			current_item.quantity -= 1
		elsif current_item.quantity = 1
		    current_item.destroy
		end
	   	current_item
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :foods
	belongs_to :restaurant
end

app/models/food.rb
class Food < ApplicationRecord
	has_many :line_items
	has_many :orders, through: :line_items
	belongs_to :user
	belongs_to :restaurant
	belongs_to :category

	before_destroy :ensure_not_referenced_by_any_line_item
	
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i, 
		message: 'must be a URL for GIF, JPG, or PNG image.'
	}

	private 
		# ensure that there are no line items referencing this product 
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty? 
				errors.add(:base, 'Line Items present')
				throw :abort
			end 
		end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :food, optional: true
  belongs_to :cart

  def total_price
  	food.price * quantity 
  end

  private

   def check_qty
     self.destroy if self.qty.zero?
   end

end

app/models/only_admins.rb
class OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.role == "superadmin" || user.role = "admin"
  end
end

app/models/only_my_account.rb
class OnlyMyAccount < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.role == "superadmin" || user.role = "admin"
  end

  def scope_collection(collection, action = Auth::READ)
    if user.role == "superadmin"
      collection
    elsif user.role == "admin"
      collection.where(restaurant_id: user.restaurant_id)
    end
  end
end

app/models/opening_hour.rb
class OpeningHour < ApplicationRecord
  belongs_to :restaurant
end

app/models/order.rb
class Order < ApplicationRecord
	enum pay_type: {
		"Check"				=> 0,
		"Credit card"		=> 1, 
		"Purchase order"	=> 2
	}

	has_many :line_items, dependent: :destroy
	belongs_to :restaurant 
	belongs_to :user

	validates :address, presence: true
	validates :pay_type, inclusion: pay_types.keys
	
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :foods
	has_many :categories
	has_many :orders
	has_many :reviews
	has_many :opening_hours
	has_one :user
	has_and_belongs_to_many :areas
	has_many :restaurant_images

	validates :name, :address, :estimated_delivery_time,  presence: true

	has_attached_file :image, styles: { large: "600x600>", medium: "180x195>", thumb: "100x100#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	def self.search(search)
  		where("name LIKE ? OR city LIKE ? OR area LIKE ?", "%#{search}%","%#{search}%", "%#{search}%") 
	end

  	geocoded_by :full_street_address
  	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  	def full_street_address
  		[area, address, city].join(', ')
	end

	
end
 

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
	after_destroy :ensure_an_admin_remains
  
  has_many :authorizations 
  has_many :reviews, dependent: :destroy
  has_many :foods  
  has_many :orders, dependent: :destroy
  has_many :line_items
  has_one :cart
  belongs_to :restaurant
  accepts_nested_attributes_for :restaurant
	


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end 
  end  


  # Returns the hash digest of the given string. 
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token 
    SecureRandom.urlsafe_base64
  end 

  def remember 
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest. 
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget 
    update_attribute(:remember_digest, nil)
  end

  	private 
  		def ensure_an_admin_remains 
  			if User.count.zero? 
  				raise Error.new "Cant't delete last user"
  			end
  		end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  	before_action :set_category, only: [:show, :edit, :update, :destroy]
  	before_action :set_restaurant

  	

  	def show 
  	end

  	def new
  		@category = Category.new
  	end

  	def edit 

  	end

  	def create
	    @category = Category.new(category_params)
	    @category.restaurant_id = @restaurant.id

	    respond_to do |format|
	      if @category.save
	        format.html { redirect_to @restaurant }
	        format.json { render :show, status: :created, location: @Category }
	      else
	        format.html { render :new }
	        format.json { render json: @category.errors, status: :unprocessable_entity }
	      end
	    end
  	end

  	def update
	    respond_to do |format|
	      if @category.update(category_params)
	        format.html { redirect_to @restaurant }
	        format.json { render :show, status: :ok, location: @category }
	      else
	        format.html { render :edit }
	        format.json { render json: @category.errors, status: :unprocessable_entity }
	      end
	    end
  	end

  	def destroy
	    @category.destroy
	    respond_to do |format|
	      	format.html { redirect_to @restaurant, notice: 'Category was successfully destroyed.' }
	      	format.json { head :no_content }
	    end
  	end 
  	
  	private
		  def set_category
      		@category = Category.find(params[:id])
    	end
    	
    	def set_restaurant
      		@restaurant = Restaurant.find(params[:restaurant_id])
    	end
    	
    	def category_params
      		params.require(:category).permit(:name)
    	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for([@restaurant, @category]) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="jumbotron" id="jumbotron1">
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<h1>Editing Category</h1>

			<%= render 'form', category: @category %>

			<%= link_to 'Show', @category %> |
			<%= link_to 'Back', restaurant_path(@restaurant) %>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', restaurant_category_path(@restaurant, category) %></td>
        <td><%= link_to 'Edit', edit_restaurant_category_path(@restaurant, category) %></td>
        <td><%= link_to 'Destroy', restaurant_category_path(@restaurant, category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_restaurant_category_path(@restaurant, Category) %>

app/views/categories/new.html.erb
<div class="jumbotron" id="jumbotron1">
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<h1>New Category</h1>

			<%= render 'form', category: @category %>

			<%= link_to 'Back', restaurant_path(@restaurant), class: "add-link" %>
				
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_restaurant_category_path(@restaurant, @category) %> |
<%= link_to 'Back', restaurant_categories_path(@restaurant, @category) %>